### ISSUE TITLE
As a developer, I want to discuss potential features for Sprint 1.

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/ministocks#1]
[Priority: 1]
[SP: 3]
[Risk: Med]

As a developer, I want to discuss potential features for Sprint 1.

Tasks:

Brainstorm and come up with a list of features to show TA
Present list to Max during meeting
Get a signoff on a feature for Sprint 2.

**Comment by Nick9500** [comment]
**Resizing** was discussed as a possible feature.

**Comment by CristiArde** [comment]
We finalized our decision on refresh or auto refresh with  scroll up and down.
Sample of how widget may look

![390feature1](https://user-images.githubusercontent.com/6819864/35548305-8b139068-054c-11e8-8f0d-190a8b4a4bb6.png)
