### ISSUE TITLE
As a User, I want to scroll through multiple stocks

### ISSUE THREAD

**Issue by GurkomalSRao** [Nick9500/ministocks#12]
As a user, I want to be able to scroll through multiple stocks that have been added
[**SP**: 10]
[**Priority**: 1]
[**Risk**: High]

**_Demo_**
Scenario 1: User swipes horizontally to scroll through stocks added on main menu

**_Task Estimation (Hours)_**
**Task 1**: Research how to add scroll bar to widget (.1h)
**Task 2**: Discuss with assignee's (.5h) 
**Task 3**: Implement scroll feature (.5h)
**Task 4**: Validate potential flaws i.e. infinite scrolling or scrolling with little to no stocks listed (1h)
**Task 5**: Modify and review with assignee's (1.5h)

**_Testing Template_**

Test # | Input | Expected Output | Status
-- | -- | -- | --
1 | None | None  | Pass/Fail
2  | None  | None  | Pass/Fail
3 | None  |None  | Pass/Fail

**Comment by GurkomalSRao** [comment]
Sample of Demo
![390feature1](https://user-images.githubusercontent.com/6819864/35549565-2728b698-0554-11e8-8b8f-eb80517f1e01.png)

**Comment by Nick9500** [comment]
Experiencing difficulty refactoring code to a GridView/ListView to display stocks. Existing code was hardcoded using 5 or 10 TextView-based elements (depending on widget size) rather than a data structure holding stocks so scalability is very very bad in pre-existing code.

**Comment by GurkomalSRao** [comment]
All views and Data was hard coded. Implementing our own functionality, at this point, does not seem feasible. 

Attempted the following procedures:

**Scenario 1**: 

- Create an ArrayList that receives all rows of the widget (String Values)
- Create an Intent that is connected to Remote View Service
- Remote View Service calls Remote View Factory
- Remote View Factory creates the structured list using the ArrayList

**Scenario 2:** 

- Create an ArrayList that receives all rows of the widget (String Values)
- Create an Intent
- Create a Pending Intent that will be sent to Remote Service
- Call the Pending Intent within Remote Service
- Remote View Service calls Remote View Factory and sends the pending intent values
- Remote View Factory creates the structured list using the values received

**Scenario 3**:

- Refactor entire view using a newly created AppProvider, Remote Service, RemoteFactory.

Scenarios 1 and 2 would not allow any connections from WidgetView and RemoteService (compilation errors)
Scenario 3 not plausible due to intensive hard coding and class manipulation done by original creator of widget source code

**Comment by Nick9500** [comment]
Completely new widget view in progress.

![](https://cdn.discordapp.com/attachments/227609919535185932/412433900498059287/wgw.jpeg)

**Comment by Nick9500** [comment]
Widget pulls stock information from another instance of original widget.
![stsc](https://user-images.githubusercontent.com/4484946/36107249-73d7f8b2-0fe7-11e8-91bd-8317f27e8e2f.jpeg)

**Comment by Nick9500** [comment]
Left to do:
-Make new widget layout standalone by allowing stocks to be set through new widget layout. IE. Pull up the Preferences Activity via button press, double tap, etc. 
-Find a way to format columns better than using string concatenation and spaces.
-Write tests for new methods/functionality (if applicable)

**Comment by Nick9500** [comment]
**Recommend** taking another 4 story points in Sprint 3 to finish story. Original estimation was way underestimated considering Risk Level due to knowledge and lack of scalability of original app.

**Comment by Nick9500** [comment]
Story has been extended to Sprint 3 to finish as discussed in meeting on Feb. 12.

**Comment by Nick9500** [comment]
ListView widget is now standalone!

To demo:
-Long press the home screen
-Add any ministocks widget
-Tap slightly below the widget to open preferences (Button to be added in future)
-Stocks can be added/modified as usual via preferences
