### ISSUE TITLE
As a Dev, I want to discuss potential features for next sprint

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/ministocks#17]
As a Dev, I want to discuss potential features for next sprint
[SP: 1]
[Priority: 1]
[Risk: Medium]

Task Estimation (Hours)
Discuss with team (0.5)

**Comment by Nick9500** [comment]
Last night, we have spoken of 3 possibilities:

1. Implementing a cryptocurrency API as a new data source.
2. Resizing widget with dynamically increasing/decreasing column# based on widget size.
3. Email updates

**Comment by GurkomalSRao** [comment]
Final Tasks are as follows:
Task 1: Finish implementing a fully functioning scroll-able widget view 
Task 2: Email Updates and/or user porfolio
