### ISSUE TITLE
As a User, I want to be able to send email notifications

### ISSUE THREAD

**Issue by GurkomalSRao** [Nick9500/ministocks#19]
As a User, I want to be able to send email notifications
[**SP**: 12]
[**Priority**: 2]
[**Risk**: High]

**_Demo_**
**Scenario 1**: User selects "send email notification" button
**Scenario 2**: User receives email of notification/porfolio

**_Task Estimation (Hours)_**
**Task 1**: Research how to implement email notification on widget (1h)
**Task 2**: Discuss with assignee's (.5h) 
**Task 3**: Implement emailing feature (2h)
**Task 4**: Validate potential flaws i.e email never received (2h)
**Task 5**: Modify and review with assignee's (1.5h)

**_Testing Template_**

Test # | Input | Expected Output | Status
-- | -- | -- | --
1 | None | None  | Pass/Fail
2  | None  | None  | Pass/Fail
3 | None  |None  | Pass/Fail

**Comment by GurkomalSRao** [comment]
Possible code for sending email 

```
Intent intent = new Intent(Intent.ACTION_SENDTO, Uri.fromParts(
            "mailto","email@email.com", null));
intent.putExtra(Intent.EXTRA_SUBJECT, subject);
intent.putExtra(Intent.EXTRA_TEXT, message);
startActivity(Intent.createChooser(intent, "Choose an Email client :"));
```

**Comment by GurkomalSRao** [comment]
Demo:
![sad](https://user-images.githubusercontent.com/6819864/36182069-c80849a0-10f5-11e8-8c04-c38b67e17cf9.jpeg)

**Comment by GurkomalSRao** [comment]
Test # | Input | Expected Output | Status
-- | -- | -- | --
1 | Select Export| Ability to Choose email address| Pass
2 | Send Email| Receive Email| Pass
3 | Open CSV| View Correct Portfolio| Pass

**Changes to be implemented**

- remove price and volume (in the future we will add #of stocks bought + price bought at in csv)
- make it so the receiver is the email you are logging into (currently when you log in the sender is the email you log into)
- make test file for emailing

**Comment by jeffersoncasimir** [comment]
We have opted to using the javax.mail library to send e-mails on behalf of a gmail account created for this app. When the user clicks the option in the Preferences menu, they are prompted with a dialog in which they enter the destination address.

This feature/issue is separate from importing and is now completed.
