### ISSUE TITLE
As a developer, I want to set up my development environment and run existing tests.

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/ministocks#2]
[Priority:1]
[SPS: 3]

As a developer, I want to set up my development environment and run existing tests.

Tasks:

Set up dev environment and Android Studio IDE.
API 27, Nexus 5X for those using Emulator.
Build and install the Ministocks widget.
Run existing tests and report results.

**Comment by githubRaj** [comment]
All team members have setup their environment and ran the tests.
