### ISSUE TITLE
As a user, I want a graphical view of my stocks

### ISSUE THREAD

**Issue by GurkomalSRao** [Nick9500/ministocks#20]
As a user, I want a graphical view of my stocks
[**SP**: 7]
[**Priority**: 1]
[**Risk**: High]

**_Demo_**
**Scenario 1**: User selects preferences
**Scenario 2**: User selects stock 
**Scenario 2**: User views graphical stock information 

**_Task Estimation (Hours)_**
**Task 1**: Research how to implement graphical view (3h)
**Task 2**: Discuss with assignee's (1h) 
**Task 3**: Implement graph view feature (5h)
**Task 4**: Validate potential flaws i.e incorrect information input in graph (4h)
**Task 5**: Modify and review with assignee's (2h)

**_Testing Template_**

Test # | Input | Expected Output | Status
-- | -- | -- | --
1 | None | None  | Pass/Fail
2  | None  | None  | Pass/Fail
3 | None  |None  | Pass/Fail

**Comment by GurkomalSRao** [comment]
Demos:

![image](https://user-images.githubusercontent.com/6819864/36181463-e9f2f798-10f2-11e8-9801-56eb2e965592.png)


![image](https://user-images.githubusercontent.com/6819864/36181470-f9354c42-10f2-11e8-8d72-c045aa535251.png)

**Comment by Nick9500** [comment]
PHASE 1

![prototype](https://user-images.githubusercontent.com/4484946/36645065-47adc07e-1a31-11e8-8688-218d392b2bfd.jpeg)

**Comment by Nick9500** [comment]
PHASE 1.5 (mini fix for rows)
![hshsh](https://user-images.githubusercontent.com/4484946/36646627-df9641ac-1a47-11e8-9ede-d5fdd992178c.jpeg)

**Comment by GurkomalSRao** [comment]
graphical information will be pulled from https://www.alphavantage.co
**API Key**: ZKD8M6L9CEQAK89H


Task 1: retrieve JSON file from URL
Task 2: parse JSON file
Task 3: acquire time series data
Task 4: apply JSON data to our graph

to parse JSON we will use https://github.com/google/gson

**Comment by Nick9500** [comment]
![aasa](https://user-images.githubusercontent.com/4484946/36773095-e121840c-1c25-11e8-9ecd-1b3b7459d684.jpeg)
