### ISSUE TITLE
As a developer, I want to have Class Diagrams and Component Diagrams in the Repo

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/ministocks#5]
[Priority: 1]
[SP: 2]
[Risk: Med]

As a developer, I want to have Class Diagrams and Component Diagrams in the Repo

Tasks:

Create a docs folder in root
Upload Component Diagram as Jpeg in a Docs folder
Upload Class Diagram as Jpeg in a Docs folder

**Comment by Nick9500** [comment]
Be sure to write "#5" somewhere in the commit message/title to reference this issue. Thank you!

**Comment by GurkomalSRao** [comment]
Component Diagram added #7 
Class Diagrams Added #8
