### ISSUE TITLE
As a Developer, I want to investigate adding a crypto API for Sprint 6

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/ministocks#51]
We are currently looking for  the next feature to add in Sprint 6. We have spoken about adding a crypto API since the beginning. Now that we have more experience with handling android widgets, we decided to look again on how to approach this problem. As a developer, I want to investigate adding a crypto API for the next Sprint.

SP: 6]
[Priority: 1]
[Risk: Medium]

Demo
N/A (under the hood)

Tasks:
Investigate which free Crypto API would be easiest to pull data from
Investigate if we need to re-implement the data pulling system, enhance Nitezh's, or meet halfway.

**Comment by Nick9500** [comment]
AlphaVantage (what we are using for Graphs) has Crypto capabilities.

**Comment by GurkomalSRao** [comment]
**Task 1)** Investigate how Yahoo and Google store stock values within application (important method calls and implementation)
Reference ( #55)
**Task 2)** Construct test cases which give proper live data of cryptocurrency using AlphaVantage API
Reference ( #57)
**Task 3)** Incorporate Cryptocurrency in stock suggestions list (search field of adding stocks in portfolio)
Reference ( #54 )
**Task 4)** Implementation of adding cryptocurrency from portfolio
Reference ( #59)
**Task 5)** Implementation of removing cryptocurrency from portfolio
Reference ( #60)
