### ISSUE TITLE
As a Developer, I want to add Crypto ticker symbols into StockSuggestions

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/ministocks#54]
We want to have the database of symbols for Cryptocurrencies show up within the StockSuggestions text field once the user begins typing, similar as it is now for stocks. As a developer, I want to add Crypto ticker symbols into StockSuggestions.

[SP: 5]
[Priority: 1]
[Risk: High]

Demo
Open widget
Open Preferences
Tap Stock Setup
Start typing BTC (for bitcoin)
Tap on BTC - Bitcoin in the suggestions

Tasks:
Find an API to pull Crypto from (maybe AlphaVantage)
Parse JSON for symbol
Create a Repo similar to YahooFinanceStockRepo
Get the same data as Nitezh (price, vol, name, etc)
Create widget row based on new Crypto info
Add to list

**Comment by everlybolivar** [comment]
Mock-up of how the stock ticker will be available to the user
![screen shot 2018-04-03 at 3 45 41 pm](https://user-images.githubusercontent.com/23622892/38272095-3c2909d8-3756-11e8-889f-bdbf3846d190.png)

**Comment by GurkomalSRao** [comment]
completed
