### ISSUE TITLE
As a Developer, Investigate the methodology in which Yahoo and Google stocks are stored within the application

### ISSUE THREAD

**Issue by GurkomalSRao** [Nick9500/ministocks#55]
Investigate which methods would be called/used if we incorporate cryptocurrencies within the widget. Currently, only stocks within the stock market are listed within the application. Incorporating cryptocurrencies would require a separate data provider. 

SP: 3]
[Priority: 1]
[Risk: Low]

Demo
Demonstrate important method calls and explain the importance of understanding them

Tasks:
Investigate methods that manipulate the values received from Google and Yahoo API
Investigate where they are stored
Investigate how they are stored
Investigate if we need to re-implement the data pulling system, enhance Nitezh's, or meet halfway.

**Comment by Nick9500** [comment]
Investigation complete. Crypto integrated into application using similar fashion to Nitezh.
