### ISSUE TITLE
As a Developer, I want to add Newsfeed functionality to the Chart

### ISSUE THREAD

**Issue by Nick9500** [Nick9500/ministocks#56]
We want to have add the functionality where if you click on a stock, it opens the Chart window popup by default but now we want to add an additional tab/button that switches the popup to an RSS feed with links relevant to the stock ticker selected. 

[SP: 5]
[Priority: 1]
[Risk: High]

Demo:
Open Widget
Open Preferences
Open Stock Setup
Add a Stock
Return to Widget
Tap on Stock
Tap on News tab/button to see list of news

Tasks:
Find a way to retrieve RSS feeds relevant to specific stock selection
Populate a new view with these clickable links
Ensure that when user clicks links, opens default browser to corresp. url

![rss mockup](https://user-images.githubusercontent.com/23041234/37859868-432bfe9c-2ef1-11e8-9bbd-0ed22967123e.PNG)

**Comment by CristiArde** [comment]
added mockup pictures

**Comment by CristiArde** [comment]
alternative can be through preferences button 
![rss preferences mockup](https://user-images.githubusercontent.com/23041234/37859890-91617470-2ef1-11e8-820c-198153a2a93b.PNG)

**Comment by Nick9500** [comment]
Mockup will be updated shortly. Newsfeed button will not be within Prefs but rather inside the chart popup window and news will be specific to certain stock not general to all in list. More concentrated this way.

**Comment by Nick9500** [comment]
Will need to be finished in Sprint 6. I underestimated complexity since risk was high so needs to be extended to Sprint6. Recommend another 4 SPs.

**Comment by everlybolivar** [comment]
Updated mockups for the Newsfeed functionality can be seen as:
![rssmock1](https://user-images.githubusercontent.com/23622892/38276263-67c3060a-3762-11e8-84fd-79047f1f8f2e.png)     ![rssmock2](https://user-images.githubusercontent.com/23622892/38276264-67d57e70-3762-11e8-81ff-09fc7dff231f.png)

**Comment by Nick9500** [comment]
![image](https://user-images.githubusercontent.com/4484946/38341767-4195c814-3848-11e8-9c95-e6b06f6350f6.png)

**Comment by Nick9500** [comment]
![sfaa](https://user-images.githubusercontent.com/4484946/38381900-4c5954b2-38d6-11e8-8ea3-f32847b3d860.jpeg)
